-- MySQL Script generated by MySQL Workbench
-- Tue Jun 13 16:14:35 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ParkingManager
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ParkingManager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ParkingManager` DEFAULT CHARACTER SET utf8 ;
USE `ParkingManager` ;

-- -----------------------------------------------------
-- Table `ParkingManager`.`Tipo_Vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ParkingManager`.`Tipo_Vehiculo` (
  `idTipoVehiculo` INT NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idTipoVehiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ParkingManager`.`Vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ParkingManager`.`Vehiculo` (
  `placa` VARCHAR(10) NOT NULL,
  `idTipoVehiculo` INT NOT NULL,
  `marca` VARCHAR(50) NULL,
  `color` VARCHAR(25) NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`placa`),
  INDEX `fk_vehiculo_tipo_vehiculo_idx` (`idTipoVehiculo` ASC),
  CONSTRAINT `fk_vehiculo_tipo_vehiculo`
    FOREIGN KEY (`idTipoVehiculo`)
    REFERENCES `ParkingManager`.`Tipo_Vehiculo` (`idTipoVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ParkingManager`.`Estancia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ParkingManager`.`Estancia` (
  `idEstancia` INT NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(10) NOT NULL,
  `fechaIngreso` DATETIME NOT NULL,
  `fechaSalida` DATETIME NOT NULL,
  `tiempo` INT NOT NULL,
  PRIMARY KEY (`idEstancia`),
  INDEX `fk_Estancia_Vehiculo_idx` (`placa` ASC),
  CONSTRAINT `fk_Estancia_Vehiculo`
    FOREIGN KEY (`placa`)
    REFERENCES `ParkingManager`.`Vehiculo` (`placa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ParkingManager`.`Pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ParkingManager`.`Pago` (
  `idPago` INT NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(10) NOT NULL,
  `fechaPago` DATETIME NOT NULL,
  `monto` DECIMAL(12,2) NOT NULL,
  `descripcion` NVARCHAR(250) NULL,
  PRIMARY KEY (`idPago`),
  INDEX `fk_Pago_Vehiculo_idx` (`placa` ASC),
  CONSTRAINT `fk_Pago_Vehiculo`
    FOREIGN KEY (`placa`)
    REFERENCES `ParkingManager`.`Vehiculo` (`placa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '		';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
